### ISSUE TITLE
Add "silent" argument to phone() to suppress status bar? 

### ISSUE THREAD

**Issue by mac471** [socialresearchcentre/dialr#20]
This is a great package - thank you.

Is it possible to consider adding a "silent" argument to phone() that would suppress the status bar output in a future release?

When using these functions in automated scripts that output to log files, you end up with logs full of partially drawn status bars.

Thanks!

**Comment by gorcha** [comment]
Thanks for the kind words!

Currently the progress bar display is controlled via the `dialr.show_progress` option, but it should only display in interactive sessions either way.
https://github.com/socialresearchcentre/dialr/blob/af0eeb17cd5d9499e0f4a38b4990c1e3c7b86b11/R/phone.R#L90

It seems like R is treating your session as interactive - in that case you can set `dialr.show_progress` to `FALSE` to forcibly hide the progress bars like so:
```r
library(dialr)

x <- c(0, 0123, "0404 753 123", "61410123817", "+12015550123")

phone(x, "AU")
#> |======================================================================| 100%
#> # Parsed phone numbers: 5 total, 4 successfully parsed
#> [1] 0            123          0404 753 123 61410123817  +12015550123

options(dialr.show_progress = FALSE)

phone(x, "AU")
#> # Parsed phone numbers: 5 total, 4 successfully parsed
#> [1] 0            123          0404 753 123 61410123817  +12015550123
```

**Comment by mac471** [comment]
Thanks for the quick response. Setting options(dialr.show_progress=FALSE) works perfectly!

**Comment by gorcha** [comment]
No worries, happy to help!
