### ISSUE TITLE
Check invalid phone numbers

### ISSUE THREAD

**Issue by winteng** [socialresearchcentre/dialr#26]
A suggestion from @storm-l - can we mark phone numbers like 0499999999 or 0400000000 as invalid phone numbers? Currently it's flagged as valid phones.

`> dialr::is_valid(dialr::phone(c('0400000000','0411111111','0499999999'),'AU'))`
`|======================================================================| 100%`
`[1] TRUE TRUE TRUE `

**Comment by gorcha** [comment]
Hey @winteng, hope you're well!

This is out of the scope of dialr - dialr is a front end to [libphonenumber](https://github.com/google/libphonenumber), and its role is to translate between the library and R. libphonenumber handles all of the actual validation.
All of these phone numbers are technically valid according to the ranges allocated by ACMA, so they'll pass the validation checks (they're more like "unlikely" numbers than "invalid").

**Comment by winteng** [comment]
Didn't expect to get a reply from you @gorcha !
OK then this should go into `srcsample::phone_clean` I supposed. 
@dlope

**Comment by gorcha** [comment]
Haha yeah despite this living in the SRC org account I'm the CRAN maintainer for dialr and dialrjars so still responsible  :stuck_out_tongue:
