### ISSUE TITLE
`phone` freezes when handling blanks

### ISSUE THREAD

**Issue by kinto-b** [socialresearchcentre/dialr#27]
Very hard for me to properly describe this issue, since it doesn't produce an error message and I can't reliably recreate it. 

But when you run this code on different machines it just hits a wall at a certain point: CPU usage goes to 99% and the parsing slows to a crawl. 

For me it took about 475 iterations to stall, but for others it stalled out after less than 50 iterations

```r
options(dialr.show_progress = FALSE)
for (i in 1:1000) {
  cat(".")
  dialr::phone(rep("+", 1000), "AU")
}
```

**Comment by gorcha** [comment]
This is a weird one! Couldn't tell you why it's stalling everything, but it's something to do with catching the java exceptions.

I get the same behaviour with `""` (although not `NA`) and also with `"+001234"`, which throws an invalid country code exception in java. Pretty sure I've got a fix that works.

**Comment by gorcha** [comment]
@kinto-b I've pushed a fix - let me know if you still have any issues

**Comment by kinto-b** [comment]
Super odd.

On a related note:
* It might be useful to handle blanks separately as they don't require parsing:

``` r
phone2 <- function(x, region = "AU") {
    blank <- x %in% c("", NA, "+")
    out <- rep(dialr::phone("", "AU"), length(x)) 
    
    if (sum(!blank, na.rm = TRUE) > 0) {
        non_blank <- dialr::phone(x[!blank], region)
        out[!blank] <- non_blank
    }
    
    out
}

options(dialr.show_progress = FALSE)
bench::mark(
    phone2(rep("", 10000)),
    dialr::phone(rep("", 10000), region = "AU")
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 x 6
#>   expression                                       min   median `itr/sec`
#>   <bch:expr>                                  <bch:tm> <bch:tm>     <dbl>
#> 1 phone2(rep("", 10000))                       496.8us  515.3us  1782.   
#> 2 dialr::phone(rep("", 10000), region = "AU")    2.49s    2.49s     0.401
#> # ... with 2 more variables: mem_alloc <bch:byt>, gc/sec <dbl>
```

<sup>Created on 2021-08-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

* To that end, it would be good to have a method for creating empty `phone()` vectors like such:

```r
character()
#> character(0)

phone()
#> phone(0)
```

**Comment by kinto-b** [comment]
@gorcha haha, you've literally just done what I was suggesting

**Comment by gorcha** [comment]
Yah pretty much, it'll also pick up some other rando invalid numbers like `"+"`, `"0"` etc.
It's pretty much just pulling the regex that libphonenumber uses out of Java into R to avoid calling up Java when it's going to throw an exception anyway.

Re: the second point, can you please open a separate issue?
